### PR TITLE
tidyed up solution and git

### PR DESCRIPTION
**Pull request by tbertenshaw**
Hi ok i think i see what the problem might be. because the gitignore didn't exclude the packages folder, some where checked in rather than being nuget references. I've just done the following.

- [x] added packages and .vs folders to the git ignore
- [x] deleted the packages folder from git.
- [x] added the vsixupdater package to the nuget references
- [x] moved the integration test project from within the configtransform project (not sure how it got inside there :)) 
- [x] updated the vstools version inside the csproj to 15.

### CODE REVIEW

**Comment by tbertenshaw** [comment]
This pr ok to accept?

**Comment by theramis** [comment]
@tbertenshaw it doesn't look like your changes will get merged. 
Would it be possible for you to build the extension and share it with me? I really miss this in VS2017

**Comment by marazt** [comment]
I will try to build it under VS2017 and create a new version today.

**Comment by tbertenshaw** [comment]
Excellent hope it builds ok.

**Comment by marazt** [comment]
New [version v1.4.0.0 released](https://marketplace.visualstudio.com/items?itemName=marazt.ConfigTransformation).

**Pull request merged**
